export const GET_SPEAKER_LISTING_SUCCESS    = 'events/GET_SPEAKER_LISTING_SUCCESS'
export const GET_SPEAKER_LISTING_FAIL       = 'events/GET_SPEAKER_LISTING_FAIL'
export const RESET_GET_SPEAKER_LISTING      = 'events/RESET_GET_SPEAKER_LISTING'
