export const GET_PROFILE         = 'profile/GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'profile/GET_PROFILE_SUCCESS';
export const RESET_GET_PROFILE   = 'profile/RESET_GET_PROFILE';

export const POST_EDIT_PROFILE         = 'profile/POST_EDIT_PROFILE';
export const POST_EDIT_PROFILE_SUCCESS = 'profile/POST_EDIT_PROFILE_SUCCESS';
export const POST_EDIT_PROFILE_FAIL    = 'profile/POST_EDIT_PROFILE_FAIL';
export const RESET_POST_EDIT_PROFILE   = 'profile/RESET_POST_EDIT_PROFILE';

export const GET_EMERGENCY_CONTACT         = 'profile/GET_EMERGENCY_CONTACT';
export const GET_EMERGENCY_CONTACT_SUCCESS = 'profile/GET_EMERGENCY_CONTACT_SUCCESS';
export const RESET_GET_EMERGENCY_CONTACT   = 'profile/RESET_GET_EMERGENCY_CONTACT';

export const POST_EDIT_EMERGENCY_CONTACT         = 'profile/POST_EDIT_EMERGENCY_CONTACT';
export const POST_EDIT_EMERGENCY_CONTACT_SUCCESS = 'profile/POST_EDIT_EMERGENCY_CONTACT_SUCCESS';
export const POST_EDIT_EMERGENCY_CONTACT_FAIL    = 'profile/POST_EDIT_EMERGENCY_CONTACT_FAIL';
export const RESET_POST_EDIT_EMERGENCY_CONTACT   = 'profile/RESET_POST_EDIT_EMERGENCY_CONTACT';

export const POST_CHANGE_PASSWORD         = 'profile/POST_CHANGE_PASSWORD';
export const POST_CHANGE_PASSWORD_SUCCESS = 'profile/POST_CHANGE_PASSWORD_SUCCESS';
export const POST_CHANGE_PASSWORD_FAIL    = 'profile/POST_CHANGE_PASSWORD_FAIL';
export const RESET_POST_CHANGE_PASSWORD   = 'profile/RESET_POST_CHANGE_PASSWORD';